### PR TITLE
Update sds generated files to support sgx feature

### PR DESCRIPTION
**Pull request by Chen-Xintong**

### CODE REVIEW

**Review by ipuustin — APPROVED** [review]
LGTM. In https://github.com/intel/istio/pull/3 is there a need to update go.mod?

**Review by ipuustin — CHANGES_REQUESTED** [review]
Hmm, now looking at this again, does the `Server` type need changes too?

```
# github.com/envoyproxy/go-control-plane/pkg/server/v3
pkg/server/v3/server.go:174:9: cannot use &server{...} (type *server) as type Server in return argument:
	*server does not implement Server (missing SendCsrAndQuote method)
```

**Comment by Chen-Xintong** [comment]
sorry for missing [this](https://github.com/intel-sandbox/go-control-plane/blob/35848d472ce4fcbf61d6a13061b3231b2da3b4fc/pkg/server/v3/server.go#L182), now it can be built

**Comment by Chen-Xintong** [comment]
> LGTM. In [intel/istio#3](https://github.com/intel/istio/pull/3) is there a need to update go.mod?

Yeah, need to update pkg version in go.mod after this merged.

**Pull request merged**
